@startuml

title Paquetes MVC


package Controlador <<Folder>> {
    package Alertas <<rectangle>> {
    }
    package Botones <<rectangle>> {
    }
}

package Modelo <<Folder>> {
    package AlgoKahoot <<rectangle>>  {
    }
    package Excepciones <<rectangle>>  {
    }
    package Pregunta <<rectangle>>  {
    }
    package Puntaje  <<rectangle>> {
    }
    package Puntuadores  <<rectangle>> {
    }
    package Respuesta <<rectangle>>  {
    }
}

package Vista <<Folder>> {
}

@enduml