@startuml

state "Turno Jugador 1" as Jugador1
state "Turno Jugador 2" as Jugador2
state "Nueva ronda" as Ronda
state c <<choice>>

[*] -down-> Jugador1: Creado
Jugador1: Ronda = Ronda Actual
Jugador1 : JugadorActual = Jugador1
Jugador1 : do / Cargar respuesta
Jugador1: exit / Cambiar Jugador

Jugador1 -down-> Jugador2: Cambiar Jugador
Jugador2: Ronda = Ronda Actual
Jugador2 : JugadorActual = Jugador2
Jugador2 : do / Cargar respuesta
Jugador2: exit / Cambiar Jugador

Jugador2 --> Ronda: Cargo nueva pregunta
Ronda: Ronda = Nueva Ronda
Ronda: entry / Asignar Puntos
Ronda: do / Nueva Ronda

Ronda --> c: Hay mas preguntas
c --> [*]: [finalizado = true]
c --> Jugador1: [finalizado = false] 

@enduml