@startuml

package "Vista" {
    AlgoKahootView <|.-- App
    ContenedorBienvenido <|.- App
    ContenedorJugadores <|.-- App
    ContenedorPodio <|.-- AlgoKahootView
    ContenedorPrincipal <|.-- AlgoKahootView
    ContendorPreguntaVF <|.- ContenedorPrincipal
    ContenedorPreguntaMC <|.- ContenedorPrincipal
    ContenedorPreguntaOC <|.- ContenedorPrincipal
    ContenedorPreguntaGC <|.- ContenedorPrincipal
}

@enduml