@startuml
skinparam classAttributeIconSize 0

title MultipleChoiceClasicoRecibeUnaListaDeRespuestasYAsignaPuntos

actor Test
participant ": Enunciado" as enunciado
participant ": RespuestaMultipleChoice" as respuesta
participant ": MultipleChoice" as preguntaMC
participant ": TipoPuntajeClasico" as puntaje

activate Test

    Test -> enunciado: new("La manzana es...", {"Una Fruta", "Verde", "Roja", "Azul"})
    activate enunciado
        enunciado --> Test
    deactivate enunciado
    Test -> respuesta: RespuestaMultipleChoice({"Verde", "Roja", "Una Fruta"})
    activate respuesta
        respuesta --> Test: 
    deactivate respuesta
    Test -> respuesta: RespuestaMultipleChoice({"Roja", "Azul", "Una Fruta"})
    activate respuesta
        respuesta --> Test: 
    deactivate respuesta

    create preguntaMC
    Test -> preguntaMC: MultipleChoice("enunciado", respuestasCorrectasTres)
    activate preguntaMC
        create puntaje
        preguntaMC -> puntaje: TipoPuntajeClasicoParaMC(respuestasCorrectasTres)
        activate puntaje 
            puntaje --> preguntaMC
        deactivate puntaje
        preguntaMC --> Test
    deactivate preguntaMC

    Test -> preguntaMC: responder({respuestasCorrectasTres, respuestasCorrectasDosRespuestasIncorrectasUno})
    activate preguntaMC
        activate preguntaMC #DarkSalmon
            loop porCadaRespuesta
                preguntaMC -> respuesta: evaluar(respuestaUsuario)
                activate respuesta
                    respuesta --> preguntaMC: {aciertos, errores}
                deactivate respuesta
                preguntaMC -> puntaje: puntuar({aciertos, errores})
                activate puntaje 
                    alt (aciertosEsperados == aciertos && errores == 0)
                        puntaje --> preguntaMC: 1
                    else !(aciertosEsperados == aciertos && errores == 0)
                         puntaje --> preguntaMC: 0
                    end 
                deactivate puntaje
            end         
    deactivate preguntaMC
    preguntaMC --> Test: {1, 0}
    deactivate preguntaMC

deactivate Test


@enduml