@startuml
skinparam classAttributeIconSize 0

title verdaderoFalsoClasicoDevuelvePuntajeCorrecto

actor Test
participant ": RespuestaVerdaderoFalso" as respuesta
participant ": VerdaderoFalso" as preguntaVF
participant ": TipoPuntajeClasico" as puntaje

activate Test

    Test -> respuesta: new(True)
    activate respuesta
        respuesta --> Test
    deactivate respuesta

    Test -> respuesta: new(False)
    activate respuesta
        respuesta --> Test
    deactivate respuesta

    create preguntaVF
    Test -> preguntaVF: VerdaderoFalso(unEnunciado, respuestaCorrecta)
    activate preguntaVF
        create puntaje
        preguntaVF -> puntaje: TipoPuntajeClasico()
        activate puntaje
            puntaje --> preguntaVF
        deactivate puntaje
        preguntaVF --> Test
    deactivate preguntaVF

    Test -> preguntaVF: responder({unaRespuestaCorrecta, unaRespuestaIncorrecta})
    activate preguntaVF
        loop porCadaRespuesta
            activate preguntaVF #DarkSalmon
                preguntaVF -> respuesta: evaluar(respuesta)
                activate respuesta
                    respuesta --> preguntaVF: {aciertos, errores}
                deactivate respuesta
                preguntaVF -> puntaje: puntuar({aciertos, errores})
                activate puntaje 
                    alt (aciertosEsperados == aciertos && errores == 0)
                        puntaje --> preguntaVF: 1
                    else !(aciertosEsperados == aciertos && errores == 0)
                         puntaje --> preguntaVF: 0
                    end 
                deactivate puntaje
            deactivate preguntaVF
        end
        preguntaVF --> Test: {1, 0}
    deactivate preguntaVF

deactivate Test


@enduml