@startuml
skinparam classAttributeIconSize 0

title unaPreguntaDeVFClasicoAsignaPuntosARespuestaCorrecta

actor Test
participant "unaRespuestaCorrecta: RespuestaCorrecta" as respuesta
participant ": VerdaderoFalsoClasico" as preguntaVF

activate Test

    create respuesta
    Test --> respuesta: new("Verdadero")
    activate respuesta
        respuesta --> Test
    deactivate respuesta

    create preguntaVF
    Test --> preguntaVF: new(unEnunciado, {unaRespuestaCorrecta, unaRespuestaIncorrecta})
    activate preguntaVF
        preguntaVF --> Test
    deactivate preguntaVF

    Test -> preguntaVF: valuar(unaRespuestaCorrecta)
    activate preguntaVF
        preguntaVF -> respuesta: valorClasico()
        activate respuesta
            respuesta --> preguntaVF: 1
        deactivate respuesta
        preguntaVF --> Test: 1
    deactivate preguntaVF

deactivate Test


@enduml