@startuml
skinparam classAttributeIconSize 0

title unaPreguntaDeVFConPenalidadRecibeRespuestasYAsignaPuntos

actor Test
participant "Respuesta" as respuesta
participant ": VerdaderoFalsoConPenalidad" as preguntaVF

activate Test

    Test --> respuesta: new("Verdadero")
    activate respuesta
        respuesta --> Test
    deactivate respuesta

    Test --> respuesta: new("Falso")
    activate respuesta
        respuesta --> Test
    deactivate respuesta

    create preguntaVF
    Test --> preguntaVF: new(unEnunciado, {unaRespuestaCorrecta, unaRespuestaIncorrecta})
    activate preguntaVF
        preguntaVF --> Test
    deactivate preguntaVF

    Test -> preguntaVF: responder({{unaRespuestaCorrecta}, {unaRespuestaIncorrecta}})
    activate preguntaVF
        loop porCadaRespuesta
            preguntaVF -> preguntaVF: valuar()
            activate preguntaVF #DarkSalmon
                preguntaVF -> respuesta: valorConPenalidad()
                activate respuesta
                    respuesta --> preguntaVF: 
                deactivate respuesta
            deactivate preguntaVF
        end
        preguntaVF --> Test: {1, -1}
    deactivate preguntaVF

deactivate Test


@enduml