@startuml

state c <<choice>>

[*] --> Juego: inicia el Juego

state Juego {
    state "Turno Jugador 1" as Jugador1
    state "Turno Jugador 2" as Jugador2
    state "Nueva ronda" as Ronda

    Jugador1: Ronda = Ronda Actual
    Jugador1 : JugadorActual = Jugador1

    Jugador1 -down-> Jugador2: Cargar respuesta
    Jugador2: Ronda = Ronda Actual
    Jugador2 : JugadorActual = Jugador2

    Jugador2 --> Ronda: Cargar respuesta
    Ronda: Ronda = Nueva Ronda

    Ronda --> c: Hay mas preguntas
}

c --> [*]: [finalizado == true]
c --> Jugador1: [finalizado == false] 

@enduml