@startuml
skinparam classAttributeIconSize 0

title PreguntaNoEsRespondida

actor Ronda
participant "Pregunta" as pregunta
participant "Respuesta" as respuesta

activate Ronda
    Ronda -> pregunta: respuestaIncorrecta()
    activate pregunta
        pregunta --> Ronda: respuestaIncorrecta()
        pregunta -> respuesta: respuestaIncorrecta()
        activate respuesta
            respuesta --> pregunta: respuestaIncorrecta
        deactivate respuesta
        pregunta --> Ronda: respuestaIncorrecta
    deactivate pregunta
deactivate Ronda

@enduml