@startuml
skinparam classAttributeIconSize 0

title RespuestaVerdaderoFalsoEsEvaluada

participant "__: PreguntaVerdaderoFalso__" as PreguntaVerdaderoFalso
participant "respuestaCorrecta:\nRespuestaVerdaderoFalso" as respuesta
participant "Puntaje" as puntaje

activate PreguntaVerdaderoFalso
    PreguntaVerdaderoFalso -> respuesta: evaluar(unaRespuesta)
    activate respuesta
        respuesta -> respuesta: equals(unaRespuesta)
        respuesta -> puntaje: puntuar(aciertos, errores)
        activate puntaje
            puntaje --> respuesta: respuestaEvaluada
        deactivate puntaje
        respuesta --> PreguntaVerdaderoFalso: respuestaEvaluada
    deactivate respuesta
deactivate PreguntaVerdaderoFalso

@enduml